package: filepond_uploader
version: '1.0.0'
author: 'Friends Of REDAXO'
supportpage: github.com/FriendsOfREDAXO/filepond_uploader

requires:
    php: '>=7.4'
    redaxo: '^5.13'
    packages:
        yform: '>=4.0.0'
        metainfo: '>=2.0.0'

page:
    title: 'translate:filepond_uploader_title'
    perm: admin
    subpages:
        upload: { title: 'translate:filepond_uploader_upload' }
        settings: { title: 'translate:filepond_uploader_settings' }

default_config:
    allowed_types: 'image/*,video/*,.pdf,.doc,.docx,.txt'
    max_size: 1000
    max_files: 30
    category_id: 0

installer_ignore:
    - node_modules
    - package.json
    - package-lock.json
    - yarn.lock
    - .gitignore
    - .github
    - .git