package: yform_filepond
version: '1.0.0'
author: Your Name
supportpage: github.com/your/repo

requires:
    php: '>=7.3'
    redaxo: '^5.12'
    packages:
        yform: '>=4.0.0'

page:
    hidden: true

installer_ignore:
    - node_modules
    - package.json
    - package-lock.json
    - yarn.lock
    - .gitignore
    - .github

default_config:
    allowed_types: .pdf,.doc,.docx,.txt
    max_size: 10
    max_files: 5
