package: filepond_uploader
version: '1.0.0'
author: Your Name
supportpage: github.com/your/repo

requires:
    php: '>=7.3'
    redaxo: '^5.12'
    packages:
        yform: '>=4.0.0'
        metainfo: '>=2.0.0'  # Neu: Metainfo als Abhängigkeit

page:
    title: 'Filepond Upload'
    perm: admin
    subpages:
        upload: { title: 'Upload' }
        settings: { title: 'Einstellungen' }

installer_ignore:
    - node_modules
    - package.json
    - package-lock.json
    - yarn.lock
    - .gitignore
    - .github

default_config:
    allowed_types: .pdf,.doc,.docx,.txt
    max_size: 10
    max_files: 5